# Top-level configuration
name = "orchid"
main = "main.py"
compatibility_date = "2024-01-05"

[build]
command = "pip install -r requirements.txt && python main.py"
output = "dist"

[[build.upload]]
format = "service-worker"

[build.upload.match]
pattern = "main.py"

# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID